### PR TITLE
astype(bool) was changing 'False' to True. Fixed

### PR DESCRIPTION
**Pull request by hilaryh**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Testing
- [X] Testing is done automatically and codecov shows test coverage
- [ ] This cannot be tested automatically 

## Documentation checklist

- [ ] I have updated all documentation in the code where necessary.
- [ ] I have checked spelling in all (new) comments and documentation.
- [ ] I have added a note to RELEASE.md if relevant (new feature, breaking change, or notable bug fix).

### CODE REVIEW

**Review by joeyshuttleworth — CHANGES_REQUESTED** [review]
Extra whitespace added to L407

**Comment by joeyshuttleworth** [comment]
The bug could be to do with a type issue where there are missing values in an otherwise boolean column causing pandas to treat the column as a string where bool('False') is True.

**Comment by joeyshuttleworth** [comment]
I think you need to use 'apply' not 'map' ?

**Comment by hilaryh** [comment]
> I think you need to use 'apply' not 'map' ?

Either could work - but map does an element-wise check whereas apply would go column by column so it'd be something longer like 
`qc_df[qc_criteria].apply(lambda y: [x=='True' or x==True for x in y])`, right?

**Review by joeyshuttleworth — APPROVED** [review]

**Pull request merged**
